name: 'Run in ManyLinux Container'
description: 'Build Wheels inside ManyLinux 2014 container'
branding:
  color: blue
  icon: upload-cloud
inputs:
  script:
    description: 'Path to the script'
    required: true
runs:
  using: 'docker'
  image: 'manylinux_arm64.Dockerfile'
  args:
    - ${{ inputs.script }}
