name: Use Docker container in workflow step

on: push

jobs:
  run-inside-pypa:
    name: Run script in pypa ${{matrix}} container
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["amd64", "arm64"]
    steps:
      - uses: actions/checkout@v4
      - name: run in docker
        uses: ./.github/actions/run-in-manylinux
        with:
          script: scripts/uname-a.sh
          arch: ${{ matrix.arch }}
