name: Use Docker container in workflow step

on: push

jobs:
  run-inside-pypa-amd64:
    name: Run script in pypa amd64 container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: clone sudachipy
        run: git clone https://github.com/WorksApplications/sudachi.rs.git
      - name: run in docker
        uses: docker://quay.io/pypa/manylinux2014_x86_64
        with:
          entrypoint: scripts/build-wheels-manylinux-pgo.sh
      - name: list wheels
        run: ls sudachi.rs/python/dist/

  run-inside-pypa-arm64:
    name: Run script in pypa arm64 container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: clone sudachipy
        run: git clone https://github.com/WorksApplications/sudachi.rs.git
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - name: run in docker
        uses: docker://quay.io/pypa/manylinux2014_aarch64
        with:
          entrypoint: scripts/build-wheels-manylinux-pgo.sh
      - name: list wheels
        run: ls sudachi.rs/python/dist/
