name: Use Docker container in workflow step

on: push

jobs:
  run-inside-pypa-amd64:
    name: Run script in pypa amd64 container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run in docker
        uses: ./.github/actions/run-in-manylinux
        with:
          script: scripts/uname-a.sh
          arch: amd64

  run-inside-pypa-arm64:
    name: Run script in pypa arm64 container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run in docker
        uses: ./.github/actions/run-in-manylinux
        with:
          script: scripts/uname-a.sh
          arch: arm64
